function y = accBPFilter_commercial_5Hz(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 31-Jan-2018 01:08:36

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 0.25;  % First Stopband Frequency
    % Fpass1 = 0.75;  % First Passband Frequency
    % Fpass2 = 2;     % Second Passband Frequency
    % Fstop2 = 2.5;   % Second Stopband Frequency
    % Astop1 = 60;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 5;     % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.11789856338922 0.794994476962802; 1 0 -1 1 ...
        1.52915140910743 0.848415384122313; 1 0 -1 1 -0.873613725126944 ...
        0.482484476500439; 1 0 -1 1 1.29208261314232 0.595535908941633; 1 0 -1 1 ...
        1.05608350672637 0.378949480140219; 1 0 -1 1 -0.634007012102311 ...
        0.247486063613062; 1 0 -1 1 0.784024150510585 0.17829480831868; 1 0 -1 1 ...
        -0.360413606058764 0.0643946502072049], ...
        'ScaleValues', [0.673714000699978; 0.673714000699978; ...
        0.590719039302249; 0.590719039302249; 0.544503651318214; ...
        0.544503651318214; 0.523617057376677; 0.523617057376677; 1]);
end

s = double(x);
y = step(Hd,s);
